[mypy]
python_version = 3.12
warn_return_any = false
no_implicit_optional = false
ignore_missing_imports = true
explicit_package_bases = true

[mypy-core.*]
ignore_errors = True
[mypy-core.tools.mongodb_tools]
ignore_errors = True
